### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by pocheyeniu** [hpzhao/SummaRuNNer#2]
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    outputs = net(sents)
  File "/home/op/zhaopeng/pytorch/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/op/zhaopeng/pytorch/SummaRuNNer-master/src/model.py", line 68, in forward
    sent_features = self._avg_pooling(word_outputs, sequence_length)
  File "/home/op/zhaopeng/pytorch/SummaRuNNer-master/src/model.py", line 56, in _avg_pooling
    avg_pooling = torch.mean(data[:sequence_length[index][0], :], dim = 0)
TypeError: 'int' object has no attribute '__getitem__'

运行出错了，

**Comment by hpzhao** [comment]
版本：PyTorch:0.1.12
