### ISSUE TITLE
用ROUGE测试的时候有问题

### ISSUE THREAD

**Issue by xy-always** [hpzhao/SummaRuNNer#27]
2018-09-07 16:53:13,999 [MainThread  ] [INFO ]  Running ROUGE with command /home/xy/ROUGE/RELEASE-1                                                                                                             .5.5/ROUGE-1.5.5.pl -e /home/xy/ROUGE/RRELEASE-1.5.5/data -a -c 95 -m -n 2 -b 75 -m /tmp/tmpzgkhf8t                                                                                                             u/rouge_conf.xml
Cannot open /home/xy/ROUGE/RRELEASE-1.5.5/data/smart_common_words.txt
Traceback (most recent call last):
  File "eval.py", line 38, in <module>
    rouge()
  File "eval.py", line 33, in rouge
    output = r.convert_and_evaluate(rouge_args=command)
  File "/home/xy/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py"                                                                                                             , line 367, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/home/xy/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py"                                                                                                             , line 342, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/home/xy/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/xy/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/xy/ROUGE/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/hom                                                                                                             e/xy/ROUGE/RRELEASE-1.5.5/data', '-a', '-c', '95', '-m', '-n', '2', '-b', '75', '-m', '/tmp/tmpzgkh                                                                                                             f8tu/rouge_conf.xml']' returned non-zero exit status 2.
一直没找到原因，。。

**Comment by hpzhao** [comment]
Try:
`cd /home/xy/ROUGE/RELEASE-1.5.5/data/
rm WordNet-2.0.exc.db
./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db`
@xy-always

**Comment by hpzhao** [comment]
Try this : [Issue](https://github.com/tagucci/pythonrouge/issues/9#issuecomment-324838609)

@xy-always
