### ISSUE TITLE
当我使用test模式的时候，出现了有个错误

### ISSUE THREAD

**Issue by XuemingQiu** [hpzhao/SummaRuNNer#41]
10%|███████████████▋                                                                                                                                                   | 997/10350 [01:25<12:29, 12.48it/s]Traceback (most recent call last):
  File "main.py", line 270, in <module>
    test()
  File "main.py", line 200, in test
    prob = probs[start:stop]
IndexError: dimension specified as 0 but tensor has no dimensions
Exception ignored in: <function tqdm.__del__ at 0x7fa9a42a28c8>
Traceback (most recent call last):
  File "/home/qiuxueming/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/home/qiuxueming/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/home/qiuxueming/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/qiuxueming/anaconda3/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/qiuxueming/anaconda3/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
如何才能修改它

**Comment by XuemingQiu** [comment]
已经解决了，谢谢

**Comment by T-Atlas** [comment]
请问您最后是如何解决的？我在997也遇到了这个错误
