### ISSUE TITLE
dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by singerhe** [hpzhao/SummaRuNNer#5]
使用的是Pytorch 0.2.0版本，Mac系统，注释掉了GPU的部分代码。然后出现了下面的异常。

```
2017-11-23 17:01:50,849 [INFO] loadding train dataset
2017-11-23 17:03:18,838 [INFO] loadding validation dataset
Traceback (most recent call last):
  File "/SummaRuNNer-master/src/train.py", line 74, in <module>
    outputs = net(sents)
  File "/usr/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/SummaRuNNer-master/src/model.py", line 72, in forward
    doc = torch.transpose(self.tanh(self.fc1(doc_features)), 0, 1)
  File "/usr/local/lib/python2.7/site-packages/torch/autograd/variable.py", line 733, in transpose
    return Transpose.apply(self, dim1, dim2)
  File "/usr/local/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 80, in forward
    result = i.transpose(dim1, dim2)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by hpzhao** [comment]
这个是pytorch版本的问题，可能是接口变了，在0.1.12版本是没啥问题。最近我会改下代码，迁移到0.2版本，优化下代码^^
