### ISSUE TITLE
请问尝试使用您的模型，结果发生如下错误知道是什么问题吗？

### ISSUE THREAD

**Issue by Cheneng** [hpzhao/SummaRuNNer#6]
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    outputs = net(sents)
  File "/home/cc/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cc/Model/SummaRuNNer/src/model.py", line 72, in forward
    doc = torch.transpose(self.tanh(self.fc1(doc_features)), 0, 1)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by Cheneng** [comment]
Python 3.5.2
Pytorch 0.3.0

**Comment by DolphinAC** [comment]
把model72行改成
doc = torch.transpose(self.tanh(self.fc1(doc_features.view(1, -1))), 0, 1)

**Comment by hpzhao** [comment]
@DolphinAC 说的没错，torch.cat的默认维度行为在pytorch0.1.12和pytorch 0.3有区别，现在已经修改了

**Comment by Cheneng** [comment]
解决了，谢谢
